name: Firebase Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Install Node.js dependencies
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Deploy to Firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
